### ISSUE TITLE
Character reworks

### ISSUE THREAD

**Issue by jthemphill** [tchajed/botc-tools#14]
The Balloonist has been reworked and has a new ability! I think some other characters have been updated too. Should we update the code accordingly?

**Comment by tchajed** [comment]
Thanks for pointing this out! I already saw some discussion on Discord and updated Balloonist (including its new setup ability) in b75ceeb76b3ca55b337702aebba5f02ed728dc6e, and I also recently implemented the Harpy, Plague Doctor, and (just now) Lil Monsta ability text changes.
