### ISSUE TITLE
Night orders are wrong

### ISSUE THREAD

**Issue by jthemphill** [tchajed/botc-tools#20]
Navigate to the night order on any script:

![image](https://github.com/user-attachments/assets/0f768fd7-c2aa-4bce-b586-da10724d8e92)

You'll notice that the evil team comes last in the night order, even though all evil players should act before most good players.

**Comment by tchajed** [comment]
Looks like the nightsheet.json I was getting from https://script.bloodontheclocktower.com changed, fixing my code to handle this now.

**Comment by tchajed** [comment]
Thanks for pointing this out! Should be fixed now.

**Comment by jthemphill** [comment]
Thank you!
